/* Legacy fixture import: consumed once by the v3 migration; never used by views. */
(function (root) {
  const SEED_PROJECTS = [
    {
      id: "016",
      code: "PR-016",
      name: "Yuanhong Cinema full design & build",
      client: "Yuanhong Cinema",
      service: "Cinema design & build",
      ph: "delivery",
      lead: "Claire Wang",
      mem: ["Claire Wang", "Daniel Wu"],
      ms: {
        iso: "2026-10-18",
        label: "Acoustic commissioning",
        time: "4:00 PM",
      },
      site: "Yuanhong Plaza L3–L5, Shenyang",
      programme: "12 months",
      fee: "Lump-sum build",
      budget: "¥48.0M",
      sector: "Cinema",
      kind: "New project",
      tags: ["Cinema", "Acoustics"],
      upd: "2 hours ago",
    },
    {
      id: "029",
      code: "PR-029",
      name: "Modern Era auditorium package",
      client: "Modern Era Cinemas",
      service: "Cinema design & build",
      ph: "review",
      lead: "Claire Wang",
      mem: ["Claire Wang", "Daniel Wu"],
      ms: { iso: "2026-09-01", label: "Client sign-off", time: "4:00 PM" },
      site: "Modern Era Mall, Changchun",
      programme: "9 months",
      fee: "Lump-sum build",
      budget: "¥22.5M",
      sector: "Cinema",
      kind: "New project",
      tags: ["Cinema", "Optics"],
      upd: "4 hours ago",
    },
    {
      id: "061",
      code: "PR-061",
      name: "Paws & Care MRI suite",
      client: "Paws & Care Vet",
      service: "Medical space fit-out",
      ph: "scoping",
      lead: "Sophia Chen",
      mem: ["Sophia Chen", "Daniel Wu"],
      ms: { iso: "2026-09-03", label: "Permit package", time: "12:00 PM" },
      site: "12 Beilin Road, Harbin",
      programme: "7 months",
      fee: "Design fee + build",
      budget: "¥6.8M",
      sector: "Pet hospital",
      kind: "New project",
      tags: ["MRI", "Shielding"],
      upd: "Today",
    },
    {
      id: "068",
      code: "PR-068",
      name: "Dalian cinema site assessment",
      client: "Modern Era Cinemas",
      service: "Site assessment",
      ph: "scheduled",
      lead: "Sophia Chen",
      mem: ["Sophia Chen"],
      ms: { iso: "2026-09-05", label: "Site survey report", time: "5:00 PM" },
      site: "Xinghai Bay plot B2, Dalian",
      programme: "3 weeks",
      fee: "Fixed fee",
      budget: "¥180K",
      sector: "Cinema",
      kind: "New project",
      tags: ["Site selection", "Cinema"],
      upd: "Yesterday",
      isnew: true,
    },
    {
      id: "071",
      code: "PR-071",
      name: "Northern Lights hotel lobby & rooms",
      client: "Northern Lights Hotel",
      service: "Hotel & F&B fit-out",
      ph: "delivery",
      lead: "Claire Wang",
      mem: ["Claire Wang", "Daniel Wu"],
      ms: { iso: "2026-11-07", label: "Practical completion", time: "3:00 PM" },
      site: "88 Zhongshan Ave, Shenyang",
      programme: "8 months",
      fee: "Lump-sum build",
      budget: "¥15.2M",
      sector: "Mid hotel",
      kind: "New project",
      tags: ["Mid hotel", "Climate"],
      upd: "5 days ago",
    },
    {
      id: "030",
      code: "PR-030",
      name: "Yuanhong projection booth MEP",
      client: "Yuanhong Cinema",
      service: "Cinema design & build",
      ph: "delivery",
      lead: "Daniel Wu",
      mem: ["Daniel Wu", "Claire Wang"],
      ms: { iso: "2026-09-18", label: "Equipment install", time: "11:00 AM" },
      site: "Yuanhong Plaza L5, Shenyang",
      programme: "10 weeks",
      fee: "Lump-sum build",
      budget: "¥2.1M",
      sector: "Cinema",
      kind: "Work package",
      parentId: "016",
      tags: ["MEP", "Projection"],
      upd: "Yesterday",
    },
    {
      id: "072",
      code: "PR-072",
      name: "VitalScan checkup centre fit-out",
      client: "VitalScan Checkup",
      service: "Design & build",
      ph: "delivery",
      lead: "Claire Wang",
      mem: ["Claire Wang", "Daniel Wu"],
      ms: { iso: "2026-09-24", label: "Equipment install", time: "2:00 PM" },
      site: "VitalScan Tower floors 6–8, Dalian",
      programme: "6 months",
      fee: "Design fee + build",
      budget: "¥11.4M",
      sector: "Health checkup",
      kind: "New project",
      tags: ["Health checkup", "DR"],
      upd: "6 days ago",
    },
    {
      id: "074",
      code: "PR-074",
      name: "CT room shielding upgrade",
      client: "Lakeside Medical",
      service: "Medical space fit-out",
      ph: "scheduled",
      lead: "Sophia Chen",
      mem: ["Sophia Chen", "Daniel Wu"],
      hold: true,
      holdReason: "Awaiting radiation authority clearance",
      ms: { iso: "2026-10-02", label: "Shielding completion", time: "4:00 PM" },
      site: "Lakeside Medical B1, Changchun",
      programme: "4 months",
      fee: "Design fee + build",
      budget: "¥3.6M",
      sector: "Medical imaging",
      kind: "New project",
      tags: ["CT", "Shielding"],
      upd: "11 days ago",
    },
    {
      id: "073",
      code: "PR-073",
      name: "Modern Era Phase 1 cinema",
      client: "Modern Era Cinemas",
      service: "Cinema design & build",
      ph: "handover",
      lead: "Claire Wang",
      mem: ["Claire Wang", "Daniel Wu"],
      ms: { iso: "2026-08-21", label: "Handover pack", time: "10:00 AM" },
      site: "Modern Era Mall Phase 1, Changchun",
      programme: "11 months",
      fee: "Lump-sum build",
      budget: "¥31.0M",
      sector: "Cinema",
      kind: "New project",
      tags: ["Cinema", "Handover"],
      upd: "3 weeks ago",
    },
    {
      id: "066",
      code: "PR-066",
      name: "Ember Grill flagship dining",
      client: "Ember Grill Group",
      service: "Hotel & F&B fit-out",
      ph: "closed",
      lead: "Claire Wang",
      mem: ["Claire Wang", "Daniel Wu"],
      ms: { iso: "2026-08-14", label: "Handover pack", time: "9:00 AM" },
      site: "Ember Grill, Heping District, Shenyang",
      programme: "5 months",
      fee: "Lump-sum build",
      budget: "¥4.9M",
      sector: "Chain dining",
      kind: "New project",
      tags: ["Chain dining", "Kitchen"],
      upd: "1 month ago",
    },
  ];

  const INTAKE = [
    {
      code: "RQ-118",
      name: "Eight-screen cinema feasibility",
      client: "Yuanhong Cinema",
      service: "Site assessment",
      need: "Site survey report",
      received: "Today, 09:12",
      state: "New",
      today: true,
      owner: "Claire Wang",
      waitDays: 0,
    },
    {
      code: "RQ-117",
      name: "Pet hospital MRI expansion",
      client: "Paws & Care Vet",
      service: "Pet hospital design & build",
      need: "Permit package",
      received: "Today, 08:40",
      state: "New",
      today: true,
      owner: "Sophia Chen",
      waitDays: 0,
    },
    {
      code: "RQ-116",
      name: "CT room structural upgrade",
      client: "Lakeside Medical",
      service: "Medical space fit-out",
      need: "Shielding completion",
      received: "Yesterday, 16:20",
      state: "Reading brief",
      owner: "Sophia Chen",
      waitDays: 1,
    },
    {
      code: "RQ-115",
      name: "Northern climate hotel refresh",
      client: "Northern Lights Hotel",
      service: "Hotel & F&B fit-out",
      need: "Concept pack",
      received: "Yesterday, 11:05",
      state: "Reading brief",
      owner: "Claire Wang",
      waitDays: 1,
    },
    {
      code: "RQ-114",
      name: "VitalScan floor 9 fit-out",
      client: "VitalScan Checkup",
      service: "Design & build",
      need: "Design package",
      received: "28 Aug, 15:48",
      state: "Awaiting client",
      owner: "Sophia Chen",
      waitDays: 6,
      lastContact: "26 Aug",
    },
    {
      code: "RQ-113",
      name: "Ember Grill kitchen services",
      client: "Ember Grill Group",
      service: "Hotel & F&B fit-out",
      need: "Equipment install",
      received: "28 Aug, 10:02",
      state: "Awaiting client",
      owner: "Claire Wang",
      waitDays: 6,
      lastContact: "27 Aug",
    },
    {
      code: "RQ-112",
      name: "Modern Era optics re-commission",
      client: "Modern Era Cinemas",
      service: "Cinema design & build",
      need: "Acoustic commissioning",
      received: "27 Aug, 14:31",
      state: "Approved",
      owner: "Claire Wang",
      waitDays: 0,
    },
    {
      code: "RQ-111",
      name: "New dining brand prototype",
      client: "Ember Grill Group",
      service: "Hotel & F&B fit-out",
      need: "Concept pack",
      received: "26 Aug, 09:55",
      state: "Declined",
      owner: "Claire Wang",
      waitDays: 0,
    },
  ];

  root.FieldworkSeed = { projects: SEED_PROJECTS, enquiries: INTAKE };
})(typeof globalThis === "object" ? globalThis : this);
